/* All trip content. Edit here; the views render from this object.
   Nothing below is invented: prices, ratings and links come from the brief. */
window.TRIP = {
  meta: {
    title: "Buenos Aires",
    dates: "28 November – 2 December",
    arrive: "2026-11-28",
    depart: "2026-12-02",
    travelers: "Two travelers",
    base: "Palermo",
    summary: "Four days in Buenos Aires for two, Palermo as home base, one day across the river in Colonia del Sacramento, Uruguay. Arrival Saturday midday, departure Wednesday early morning. First visit.",
  },

  maps: (q) => "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(q + " Buenos Aires"),

  days: [
    {
      id: "sat", num: "28", weekday: "Saturday", month: "November", short: "Sat 28",
      title: "Arrival, deliberately light",
      intro: "You land at midday after a long flight. Nothing today is fixed. Settle in, walk somewhere pretty, eat something simple, sleep.",
      stops: [
        { time: "Midday", title: "Arrive and check in, Palermo", icon: "home",
          text: "Rest after the flight. No heavy plans today; jet lag is real and the trip is short enough that a slow first afternoon pays off later." },
        { time: "Afternoon", title: "Palermo Soho stroll", icon: "walk",
          text: "An easy walk through Plaza Serrano, the boutiques and the street art. No fixed itinerary, just wandering.",
          map: "Plaza Serrano Palermo Soho", area: "palermo" },
        { time: "Evening", title: "Light dinner in Palermo", icon: "fork",
          text: "Casual, not a big steak dinner. That is saved for the last night. Empanadas or a light bistro.",
          eats: ["El Preferido de Palermo", "Niño Gordo", "La Cabrera"] },
      ],
    },
    {
      id: "sun", num: "29", weekday: "Sunday", month: "November", short: "Sun 29",
      title: "The south of the city, then tango",
      intro: "Sunday is the only day the San Telmo market runs, which sets the shape of the day: market, historic centre, La Boca before dusk, then a show.",
      stops: [
        { time: "10:00", title: "Feria de San Telmo", icon: "market",
          text: "Sunday antiques and street market centred on Plaza Dorrego. It only happens on Sundays, which is why it is scheduled today.",
          travel: "~30 min from Palermo by taxi or subte", map: "Plaza Dorrego San Telmo", area: "san-telmo" },
        { time: "13:00", title: "Plaza de Mayo and Casa Rosada", icon: "landmark",
          text: "The historic centre: the presidential palace and the Cabildo. Interior tours of the Casa Rosada are not bookable at the moment, so enjoy the façade from the plaza.",
          travel: "10 min walk from the market", map: "Plaza de Mayo" },
        { time: "14:30", title: "La Boca and Caminito", icon: "camera",
          text: "The painted houses, with the Boca Juniors stadium and museum nearby. Stick to the main Caminito strip and a few surrounding blocks, and go before dusk.",
          travel: "~15 min taxi from Plaza de Mayo", map: "Caminito La Boca", area: "la-boca" },
        { time: "20:00", title: "Tango dinner show", icon: "tango", decision: "tango",
          text: "Two very different nights out. Which matters more, value or exclusivity?" },
      ],
    },
    {
      id: "mon", num: "30", weekday: "Monday", month: "November", short: "Mon 30",
      title: "Uruguay for the day",
      intro: "A ferry across the Río de la Plata to Colonia del Sacramento, a small Portuguese-Spanish old town you can cover comfortably on foot.",
      link: { route: "#/uruguay", label: "Full Uruguay day-trip guide" },
      stops: [
        { time: "~07:30", title: "Depart by ferry to Colonia del Sacramento", icon: "ferry", decision: "ferry",
          text: "Both countries' immigration is handled at the Buenos Aires terminal before boarding. Bring passports.",
          travel: "~25 min taxi from Palermo to the ferry terminal" },
        { time: "09:00–16:00", title: "Explore Colonia's old town", icon: "walk",
          text: "Barrio Histórico, the lighthouse, Calle de los Suspiros, Plaza Mayor and the ruins of the Convent of San Francisco.",
          map: "Barrio Histórico Colonia del Sacramento Uruguay", mapRaw: true },
        { time: "~17:00", title: "Return ferry to Buenos Aires", icon: "ferry",
          text: "Back in the city by evening." },
      ],
    },
    {
      id: "tue", num: "1", weekday: "Tuesday", month: "December", short: "Tue 1",
      title: "Recoleta, a landmark, and the big dinner",
      intro: "The last full day. Grand mausoleums in the morning, one landmark of your choosing, a sunset on the docks, then the dinner the whole trip has been saving up for.",
      stops: [
        { time: "09:30", title: "Recoleta Cemetery", icon: "landmark",
          text: "Evita's grave and streets of elaborate mausoleums.",
          travel: "~15 min taxi from Palermo", map: "Recoleta Cemetery", area: "recoleta" },
        { time: "11:30", title: "MALBA or Teatro Colón", icon: "ticket", decision: "museum",
          text: "One slot, two very different Buenos Aires landmarks. Pick your afternoon." },
        { time: "17:00", title: "Puerto Madero", icon: "sun",
          text: "A sunset walk along the docks and across the Puente de la Mujer. Keep this a walk rather than a second meal stop; dinner is the big event tonight.",
          travel: "~20 min taxi", map: "Puente de la Mujer Puerto Madero", area: "puerto-madero" },
        { time: "20:30", title: "Parrilla dinner in Palermo", icon: "flame", donjulio: true,
          text: "The trip's final dinner." },
      ],
    },
  ],

  decisions: {
    tango: {
      key: "tango", eyebrow: "Decision · Sunday 20:00", title: "Tango dinner show",
      prompt: "Two very different nights out. Which matters more, value or exclusivity?",
      options: [
        { id: "porteno", name: "Tango Porteño", sub: "Platea dinner-show tier", recommended: "Recommended default",
          why: "Best value for quality. Rated 4.5–4.6, a full à la carte dinner with unlimited wine, a large live orchestra, and round-trip hotel transfer included.",
          price: "≈ $90–110 per person", rating: "4.5–4.6",
          booking: [{ label: "tango-porteno.tangoshowba.com", url: "https://tango-porteno.tangoshowba.com/" },
                    { label: "GetYourGuide", url: "https://www.getyourguide.com/s/?q=Tango%20Porte%C3%B1o%20Buenos%20Aires" }],
          map: "https://www.google.com/maps/search/?api=1&query=Tango+Porte%C3%B1o+Buenos+Aires",
          tone: "value" },
        { id: "rojo", name: "Rojo Tango", sub: "At the Faena Hotel, Puerto Madero", recommended: null,
          why: "The most exclusive, intimate tango experience in the city, with only about 100 seats. Rated 4.9 for the show; the dinner reviews are more mixed than the show itself.",
          price: "≈ $260–300 per person", rating: "4.9",
          booking: [{ label: "GetYourGuide", url: "https://www.getyourguide.com/s/?q=Rojo%20Tango%20Faena%20Buenos%20Aires" },
                    { label: "Hotel Faena", url: "https://www.faena.com/" }],
          map: "https://www.google.com/maps/search/?api=1&query=Rojo+Tango+Faena+Hotel+Buenos+Aires",
          tone: "luxury" },
      ],
    },
    museum: {
      key: "museum", eyebrow: "Decision · Tuesday 11:30", title: "Teatro Colón or MALBA",
      prompt: "One slot, two very different Buenos Aires landmarks. Pick your afternoon.",
      options: [
        { id: "colon", name: "Teatro Colón", sub: "Guided tour, about 50 minutes", recommended: "Recommended for first-timers",
          what: "World-famous opera house, 19th-century architecture.",
          why: "For architecture and history lovers, and a genuine bucket-list landmark.",
          price: "≈ $40–45 guided tour", time: "~50 min guided tour",
          booking: [{ label: "teatrocolon.org.ar", url: "https://teatrocolon.org.ar/" },
                    { label: "GetYourGuide", url: "https://www.getyourguide.com/s/?q=Teatro%20Colon%20guided%20tour" }],
          map: "https://www.google.com/maps/search/?api=1&query=Teatro+Colon+Buenos+Aires",
          photo: "teatro-colon.jpg", alt: "The gilded main hall of Teatro Colón, seen from the stalls" },
        { id: "malba", name: "MALBA", sub: "Self-paced, 1.5–2 hours", recommended: null,
          what: "Latin American modern and contemporary art museum.",
          why: "For travelers who specifically want an art-focused stop, or a return trip.",
          price: "≈ $12–15 entry, no advance ticket usually needed", time: "~1.5–2 hours, self-paced",
          booking: [{ label: "malba.org.ar", url: "https://malba.org.ar/" }],
          map: "https://www.google.com/maps/search/?api=1&query=MALBA+Buenos+Aires",
          photo: "malba.jpg", alt: "The pale stone façade of MALBA" },
      ],
    },
    ferry: {
      key: "ferry", eyebrow: "Decision · Monday", title: "Which ferry company",
      prompt: "Three operators cross to Colonia. Book two to three weeks ahead whichever you choose.",
      options: [
        { id: "buquebus", name: "Buquebus", sub: "Premium", recommended: "Closest terminal to Palermo",
          terminal: "Puerto Madero, ~25 min taxi from Palermo", crossing: "As fast as 50 min",
          price: "≈ $100–170 round trip, dynamic pricing (can double in high season if booked late)",
          best: "Convenience, the fastest crossing, and the closest terminal to Palermo.",
          booking: [{ label: "buquebus.com", url: "https://www.buquebus.com/" }] },
        { id: "coloniaexpress", name: "Colonia Express", sub: "Budget-friendly", recommended: null,
          terminal: "Further out, Dock Sud area, ~30 min taxi", crossing: "~1h to 1h15",
          price: "≈ $100–130 round trip",
          best: "Better value, still reliable.",
          booking: [{ label: "coloniaexpress.com", url: "https://www.coloniaexpress.com/" }] },
        { id: "seacat", name: "Seacat", sub: "Budget tier, same parent company as Buquebus", recommended: null,
          terminal: "Online sales mainly", crossing: "Similar to Buquebus",
          price: "Typically the cheapest of the three",
          best: "Budget-conscious travelers comfortable booking online only.",
          booking: [{ label: "seacatcolonia.com.ar", url: "https://www.seacatcolonia.com.ar/" }],
          note: "The brief's seacatcolonia.com address did not resolve when checked; the .com.ar site does." },
      ],
    },
  },

  donJulio: {
    name: "Don Julio", address: "Guatemala 4699, Palermo",
    why: "The most celebrated steakhouse in Buenos Aires, ranked in the World's 50 Best Restaurants.",
    booking: "Essential, roughly 6–8 weeks in advance, through the restaurant's official website only. Avoid third-party lookalike booking sites.",
    url: "https://www.parrilladonjulio.com/", urlLabel: "parrilladonjulio.com",
    fallback: "No booking? Queue 30–45 minutes before opening. The restaurant offers waiting guests sparkling wine and empanadas.",
    map: "https://www.google.com/maps/search/?api=1&query=Don+Julio+Palermo+Buenos+Aires",
    backup: { name: "La Cabrera", why: "Also top-rated, generally easier to get a table, generous sides included with every steak.",
              map: "https://www.google.com/maps/search/?api=1&query=La+Cabrera+Palermo+Buenos+Aires" },
    weeksAhead: [6, 8],
    dinnerDate: "2026-12-01",
  },

  uruguay: {
    formalities: [
      "Both Argentine exit and Uruguayan entry immigration are processed at the Buenos Aires ferry terminal, back to back, before boarding. There is no separate immigration on arrival in Uruguay.",
      "Bring passports.",
      "Arrive 1 to 1.5 hours before departure, and 2 hours in high season. Late November is the start of high season here, so lean toward the longer buffer.",
    ],
    advice: "Book 2 to 3 weeks ahead regardless of company. Late November is early high season; prices climb and cheap seats disappear closer to the date.",
    tour: {
      lead: "Colonia's old town is small and easily walkable, so a paid guided tour is not necessary. It is an option if you would rather not self-organise.",
      name: "Colonia del Sacramento Small-Group Day Trip", via: "Viator", rating: "≈ 4.5/5 from about 170 reviews",
      price: "≈ $250 per person", includes: "Transfers, ferry and a walking tour.",
      url: "https://www.viator.com/searchResults/all?text=Colonia%20del%20Sacramento%20Small-Group%20Day%20Trip", urlLabel: "viator.com",
    },
    schedule: [
      { time: "07:30–08:00", text: "Depart Buenos Aires." },
      { time: "09:00–09:30", text: "Arrive in Colonia. The old town is a 15–20 minute walk from the port." },
      { time: "Morning", text: "Explore the Barrio Histórico. Climb the lighthouse, walk Calle de los Suspiros, see Plaza Mayor and the ruins of the Convent of San Francisco." },
      { time: "Lunch", text: "In the old town." },
      { time: "Afternoon", text: "Optional bike rental." },
      { time: "17:00–18:00", text: "Return ferry." },
      { time: "Evening", text: "Back in Buenos Aires." },
    ],
    places: [
      { name: "Faro de Colonia del Sacramento", q: "Faro de Colonia del Sacramento Uruguay" },
      { name: "Calle de los Suspiros", q: "Calle de los Suspiros Colonia del Sacramento Uruguay" },
      { name: "Plaza Mayor", q: "Plaza Mayor Colonia del Sacramento Uruguay" },
      { name: "Convent of San Francisco ruins", q: "Ruinas Convento San Francisco Colonia del Sacramento Uruguay" },
    ],
  },

  neighborhoods: [
    { id: "palermo", name: "Palermo", tag: "Home base", photo: "palermo-rosedal.jpg", alt: "Roses in bloom at El Rosedal, Bosques de Palermo",
      text: "Soho has the boutiques, street art, and a weekend craft fair at Plaza Serrano. Hollywood is quieter by day, livelier at night for bars and restaurants. The Bosques de Palermo parks are good for a relaxed morning walk, including the Rose Garden and the Japanese Garden.",
      spots: [["Plaza Serrano", "Plaza Serrano Palermo Soho"], ["Palermo Hollywood", "Palermo Hollywood"], ["Bosques de Palermo", "Bosques de Palermo"], ["El Rosedal (Rose Garden)", "El Rosedal de Palermo"], ["Jardín Japonés", "Jardin Japones"]] },
    { id: "san-telmo", name: "San Telmo", tag: "Sunday", photo: "san-telmo-dorrego.jpg", alt: "Market stalls beneath the balconies of Plaza Dorrego",
      text: "Cobblestone streets, the Sunday antiques fair centred on Plaza Dorrego, impromptu tango dancing in the street, and the covered Mercado de San Telmo for a snack.",
      spots: [["Plaza Dorrego", "Plaza Dorrego San Telmo"], ["Feria de San Telmo", "Feria de San Telmo"], ["Mercado de San Telmo", "Mercado de San Telmo"]] },
    { id: "la-boca", name: "La Boca", tag: "Sunday, before dusk", photo: "la-boca-caminito.jpg", alt: "The painted corrugated houses of Caminito",
      text: "Stick to the Caminito strip and the immediately surrounding blocks; touristy but photogenic. The Boca Juniors stadium and museum are right there for football fans.",
      spots: [["Caminito", "Caminito La Boca"], ["La Bombonera (Boca Juniors stadium and museum)", "Estadio Alberto J. Armando La Boca"]] },
    { id: "recoleta", name: "Recoleta", tag: "Tuesday", photo: "recoleta-cemetery.jpg", alt: "A wrought-iron mausoleum gate in Recoleta Cemetery",
      text: "The cemetery is the headline. The surrounding area has a Sunday craft fair at Plaza Francia and good cafés for a break afterward.",
      spots: [["Recoleta Cemetery", "Recoleta Cemetery"], ["Plaza Francia", "Plaza Francia Recoleta"], ["La Biela", "La Biela Recoleta"]] },
    { id: "puerto-madero", name: "Puerto Madero", tag: "Tuesday sunset", photo: "puerto-madero-puente.jpg", alt: "The Puente de la Mujer footbridge over the docks of Puerto Madero",
      text: "Modern docks, the Puente de la Mujer bridge, and the ecological reserve (Reserva Ecológica Costanera Sur) for a longer waterside walk if time allows.",
      spots: [["Puente de la Mujer", "Puente de la Mujer Puerto Madero"], ["Reserva Ecológica Costanera Sur", "Reserva Ecologica Costanera Sur"]] },
  ],

  restaurants: [
    { area: "palermo", name: "Don Julio", desc: "The must-book destination parrilla. See the booking callout.", tier: "$$$$", q: "Don Julio Palermo", star: true },
    { area: "palermo", name: "El Preferido de Palermo", desc: "Classic, casual cantina. Great for a relaxed lunch or brunch.", tier: "$$", q: "El Preferido de Palermo" },
    { area: "palermo", name: "La Cabrera", desc: "Top-rated parrilla, generous sides, easier reservation than Don Julio.", tier: "$$$", q: "La Cabrera Palermo" },
    { area: "palermo", name: "Niño Gordo", desc: "Asian-Argentine fusion. A good change of pace from beef-heavy meals.", tier: "$$$", q: "Niño Gordo Palermo" },
    { area: "palermo", name: "Café Cuervo", desc: "Solid specialty coffee for mornings in Soho.", tier: "$", q: "Café Cuervo Palermo" },
    { area: "palermo", name: "Lattente", desc: "Solid specialty coffee for mornings in Soho.", tier: "$", q: "Lattente Palermo" },
    { area: "san-telmo", name: "Café San Juan", desc: "Modern bistro-parrilla with a strong local following. Good post-market lunch.", tier: "$$$", q: "Café San Juan San Telmo" },
    { area: "san-telmo", name: "Bar El Federal", desc: "Historic bar notable with a beautiful old interior. Coffee or a picada (cured meats and cheese).", tier: "$$", q: "Bar El Federal San Telmo" },
    { area: "san-telmo", name: "Café La Poesía", desc: "Historic bar notable with a beautiful old interior. Coffee or a picada.", tier: "$$", q: "Café La Poesía San Telmo" },
    { area: "san-telmo", name: "Mercado de San Telmo", desc: "Covered market, good for grazing (empanadas, Coffee Town for espresso) rather than a sit-down meal.", tier: "$", q: "Mercado de San Telmo" },
    { area: "recoleta", name: "La Biela", desc: "The classic Recoleta café, right across from the cemetery. Iconic terrace coffee or light lunch.", tier: "$$", q: "La Biela Recoleta" },
    { area: "recoleta", name: "El Ateneo Grand Splendid", desc: "A former theatre turned bookstore with a café on the old stage. Worth a stop for the architecture alone.", tier: "$", q: "El Ateneo Grand Splendid" },
    { area: "puerto-madero", name: "El Mercado", desc: "Inside the Faena Hotel. Excellent, upscale steakhouse.", tier: "$$$$", q: "El Mercado Faena Hotel Puerto Madero" },
    { area: "puerto-madero", name: "Cabaña Las Lilas", desc: "Long-established, canal-side steakhouse, popular with visitors. Book ahead.", tier: "$$$$", q: "Cabaña Las Lilas Puerto Madero" },
    { area: "puerto-madero", name: "La Parolaccia", desc: "Reliable Italian with canal views. Good if craving a break from beef.", tier: "$$$", q: "La Parolaccia Puerto Madero" },
  ],
  areaNotes: {
    "la-boca": "Treat La Boca as a walk-through stop for a quick snack or ice cream rather than a dining destination. Save your appetite for elsewhere.",
    "puerto-madero": "Don Julio is already the trip's big final dinner, so treat Puerto Madero as primarily a sunset walk rather than a second major meal.",
  },
  areaNames: { "palermo": "Palermo", "san-telmo": "San Telmo", "la-boca": "La Boca", "recoleta": "Recoleta", "puerto-madero": "Puerto Madero" },

  food: [
    { id: "empanadas", name: "Empanadas", icon: "empanada", note: "" },
    { id: "choripan", name: "Choripán", icon: "chori", note: "Chorizo sandwich, great street food." },
    { id: "provoleta", name: "Provoleta", icon: "cheese", note: "Grilled provolone, a common parrilla starter." },
    { id: "medialunas", name: "Medialunas with a café con leche", icon: "coffee", note: "Ideally at a classic café like Café Tortoni or La Biela." },
    { id: "dulce", name: "Dulce de leche", icon: "spoon", note: "In any dessert form." },
    { id: "helado", name: "Argentine-style helado", icon: "icecream", note: "Rapa Nui or Freddo are reliable chains." },
    { id: "malbec", name: "A glass of Malbec at a proper wine bar", icon: "wine", note: "Not just at dinner." },
  ],

  bookings: [
    { id: "donjulio", item: "Don Julio dinner reservation", where: [{ label: "parrilladonjulio.com", url: "https://www.parrilladonjulio.com/" }],
      price: "Included in dinner cost", urgency: "Book 6–8 weeks ahead", level: "high", note: "Highest-urgency item in this whole trip." },
    { id: "tango", item: "Tango dinner show", dynamic: "tango",
      where: [{ label: "tango-porteno.tangoshowba.com", url: "https://tango-porteno.tangoshowba.com/" }, { label: "GetYourGuide", url: "https://www.getyourguide.com/s/?q=tango%20show%20Buenos%20Aires" }],
      price: "$90–110 (Tango Porteño) / $260–300 (Rojo Tango)", urgency: "Book 2–3 weeks ahead", level: "mid" },
    { id: "ferry", item: "Ferry to Colonia, Uruguay", dynamic: "ferry",
      where: [{ label: "buquebus.com", url: "https://www.buquebus.com/" }, { label: "coloniaexpress.com", url: "https://www.coloniaexpress.com/" }, { label: "seacatcolonia.com.ar", url: "https://www.seacatcolonia.com.ar/" }],
      price: "$100–170 round trip", urgency: "Book 2–3 weeks ahead", level: "mid", note: "Prices rise closer to the date." },
    { id: "colon", item: "Teatro Colón guided tour", conditional: "museum:colon",
      where: [{ label: "teatrocolon.org.ar", url: "https://teatrocolon.org.ar/" }, { label: "GetYourGuide", url: "https://www.getyourguide.com/s/?q=Teatro%20Colon%20guided%20tour" }],
      price: "$40–45", urgency: "Book at least a few days ahead", level: "low" },
  ],
  bookingsFootnote: "Everything else (San Telmo market, Recoleta Cemetery, La Boca, Puerto Madero, and MALBA if chosen) is free or pay-on-arrival and needs no advance booking.",

  todos: [
    { id: "t-donjulio", group: "bookings", text: "Book Don Julio dinner reservation", priority: "high" },
    { id: "t-ferry", group: "bookings", text: "Book ferry to Colonia, Uruguay", priority: "high" },
    { id: "t-tango", group: "bookings", text: "Book tango dinner show", priority: "high" },
    { id: "t-decide-tango", group: "bookings", text: "Decide: Tango Porteño vs. Rojo Tango", priority: "medium", decision: "tango" },
    { id: "t-decide-museum", group: "bookings", text: "Decide: MALBA vs. Teatro Colón", priority: "medium", decision: "museum" },
    { id: "t-colon", group: "bookings", text: "Book Teatro Colón guided tour (if chosen)", priority: "medium" },
    { id: "t-passport", group: "before", text: "Check passport validity (most countries require 6 months beyond travel dates)", priority: "high" },
    { id: "t-bank", group: "before", text: "Notify bank/card provider of travel dates to Argentina and Uruguay", priority: "medium" },
    { id: "t-cash", group: "before", text: "Check ATM/currency exchange strategy for Argentine pesos", priority: "medium" },
    { id: "t-insurance", group: "before", text: "Arrange travel insurance", priority: "medium" },
    { id: "t-adapter", group: "before", text: "Check power adapter needs (Argentina uses Type C/I plugs, 220V)", priority: "low" },
    { id: "t-maps", group: "before", text: "Download offline maps for Buenos Aires and Colonia", priority: "low" },
    { id: "t-bookmark", group: "before", text: "Save this app / bookmark it for offline reference while traveling", priority: "low" },
  ],
  todoGroups: { bookings: "Bookings", before: "Before you go" },
  todoNote: "The \"Before you go\" items are general travel-admin reminders, not trip-specific research. They were not individually verified against your situation, such as your passport's validity or your bank's policies.",
};
